/**
 * Manual type declarations for Module Federation remote imports.
 * These are normally auto-generated by @module-federation/enhanced when running `bun run dev`.
 * This file ensures type-checking works without a running dev server.
 *
 * Keep in sync with ui-components component exports.
 */

declare module "ui_components/atoms/BottomBar/BottomBar" {
	import type { FunctionalComponent } from "preact";

	interface BottomBarProps {
		currentSlideIndex: number;
		totalSlides: number;
		currentSectionIndex: number;
		totalSections: number;
	}

	const BottomBar: FunctionalComponent<BottomBarProps>;
	export default BottomBar;
}

declare module "ui_components/atoms/NavArrows/NavArrows" {
	import type { FunctionalComponent } from "preact";

	interface NavArrowsProps {
		onNext: () => void;
		onPrev: () => void;
		canGoNext: boolean;
		canGoPrev: boolean;
	}

	const NavArrows: FunctionalComponent<NavArrowsProps>;
	export default NavArrows;
}

declare module "ui_components/atoms/SlideTransition/SlideTransition" {
	import type { ComponentChildren, FunctionalComponent } from "preact";

	interface SlideTransitionProps {
		transitionKey: string;
		children: ComponentChildren;
	}

	const SlideTransition: FunctionalComponent<SlideTransitionProps>;
	export default SlideTransition;
}

declare module "ui_components/molecules/CenterPanel/CenterPanel" {
	import type { ComponentChildren, FunctionalComponent } from "preact";

	interface CenterPanelProps {
		sectionLabel?: string;
		slideTitle?: string;
		slideBody?: string;
		children?: ComponentChildren;
	}

	const CenterPanel: FunctionalComponent<CenterPanelProps>;
	export default CenterPanel;
}

declare module "ui_components/molecules/DiagramPanel/DiagramPanel" {
	import type { ComponentChildren, FunctionalComponent } from "preact";

	interface DiagramMetadata {
		label: string;
		value: string;
	}

	interface DiagramPanelProps {
		panelTitle?: string;
		metadata?: DiagramMetadata[];
		children: ComponentChildren;
	}

	const DiagramPanel: FunctionalComponent<DiagramPanelProps>;
	export default DiagramPanel;
}

declare module "ui_components/molecules/Header/Header" {
	import type { FunctionalComponent } from "preact";

	interface HeaderProps {
		title: string;
		linkText?: string;
		linkUrl?: string;
	}

	const Header: FunctionalComponent<HeaderProps>;
	export default Header;
}

declare module "ui_components/molecules/Sidebar/Sidebar" {
	import type { FunctionalComponent } from "preact";

	interface SidebarSection {
		id: string;
		title: string;
		isActive: boolean;
		visitedCount: number;
		slideCount: number;
	}

	interface SidebarProps {
		sections: SidebarSection[];
		activeSectionId: string;
		onSectionClick: (sectionId: string) => void;
		appName?: string;
		version?: string;
	}

	const Sidebar: FunctionalComponent<SidebarProps>;
	export default Sidebar;
}

declare module "ui_components/organisms/PresentationLayout/PresentationLayout" {
	import type { ComponentChildren, FunctionalComponent } from "preact";

	interface PresentationLayoutProps {
		header: ComponentChildren;
		sidebar: ComponentChildren;
		center: ComponentChildren;
		diagram: ComponentChildren;
		bottom: ComponentChildren;
		navPrev?: ComponentChildren;
		navNext?: ComponentChildren;
		showDiagram?: boolean;
	}

	const PresentationLayout: FunctionalComponent<PresentationLayoutProps>;
	export default PresentationLayout;
}
